FROM agrigorev/zoomcamp-model:2025

RUN pip install pipenv

WORKDIR /app
COPY ["Pipfile","Pipfile.lock","./"]

RUN pipenv install --deploy --system

COPY ["predict.py","pipeline_v1.bin","./"]

EXPOSE 9696

ENTRYPOINT ["waitress-serve", "--host=0.0.0.0", "--port=9696", "predict:app" ]